
services:
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    networks:
      - transcendece_nw
    # env_file:
    #   - .env

  database:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_NAME: postgresql
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - transcendece_nw

networks:
  transcendece_nw:
    driver: bridge

volumes:
  pgdata: